version: '3'

services:
   web:
      restart: unless-stopped
      build: .
      image: 127.0.0.1:5000/abc_web
      ports:
         - '3001:3000'
      environment:
         env_file: .env.production
      deploy:
         replicas: 1
